### ISSUE TITLE
bitarray vs xmpz

### ISSUE THREAD

**Issue by ELind77** [rmrschub/pyEliasFano#1]
Hi,

I saw in the commit history that you switched from using `bitarray` to `xmpz` and I was wondering if you could explain what motivated that decision.

-- Eric

**Comment by rmrschub** [comment]
Hi Eric, 

mainly performance concerns: https://stackoverflow.com/questions/20845686/python-bit-array-performant
Since I switched from pyELiasFano to a C++ implementation, this argument no longer holds and I dropped xmpz...

Best, R.
